#!/bin/bash

pip install -U -r requirements.txt 
cp perf_script_processor delta_processor /usr/local/bin/
chmod +x /usr/local/bin/{perf_script_processor,delta_processor}
cp delta_processor.conf /etc/delta_processor.conf
echo "SUCCESSFULLY INSTALLED!"
