#!/bin/bash

# usage: $ ./perf_script_process.sh <dir where perf.data exists>

# $DUMP_PATH='/tmp/pp_results/'
DUMP_PATH=$1

# run perf script, grep for qemu-kvm (this can be adjusted)
# then get the timestamp and metric fields, clean them and
# dump the data in a csv file

pattern=$(grep '^order' /etc/delta_processor.conf | awk -F' ' '{print $3}' | sed s#kvm_exit#kvm_exit.*IO_#g)

if [[ ! -z $DUMP_PATH ]]; then 
    # run postprocessor on that
	if [ -f ${DUMP_PATH%/}/perf.data ]; then
		echo "Processing perf.data ..."
		perf script | grep qemu-kvm | awk -F' ' '{print $4,$5,$6,$7}' | egrep $pattern | awk -F' ' '{print $1,$2}' | \
		    sed 's/sched://g' | sed 's/kvm://g' | sed 's/syscalls://g' | \
		    sed 's/://g' | sed 's/ /,/g' > ${DUMP_PATH%/}/perf_data.csv
		# add header to csv file
		sed -i '1s/^/tstamp,entry\n/' ${DUMP_PATH%/}/perf_data.csv
	    delta_processor -i ${DUMP_PATH%/}/perf_data.csv -o $DUMP_PATH -m 3
		
	elif [ -f ${DUMP_PATH%/}/raw_perf ]; then
		echo "Processing raw_perf ..."
		cat ${DUMP_PATH%/}/raw_perf | grep qemu-kvm | awk -F' ' '{print $4,$5,$6,$7}' | egrep $pattern | awk -F' ' '{print $1,$2}' | \
		    sed 's/sched://g' | sed 's/kvm://g' | sed 's/syscalls://g' | \
		    sed 's/://g' | sed 's/ /,/g' > ${DUMP_PATH%/}/perf_data.csv
		# add header to csv file
		sed -i '1s/^/tstamp,entry\n/' ${DUMP_PATH%/}/perf_data.csv
	    delta_processor -i ${DUMP_PATH%/}/perf_data.csv -o $DUMP_PATH -m 3

	elif [ -f ${DUMP_PATH%/}/perf_data.csv ]; then
		echo "Processing perf_data.csv ..."
	    delta_processor -i ${DUMP_PATH%/}/perf_data.csv -o $DUMP_PATH -m 3
	# else
	# 	echo "ERROR! Failed to somehow write to intermediate result file perf_data.csv."
	# fi
	else
		echo "ERROR! This path doesn't contain 'perf.data'. I Quit.."
	fi
else
	echo "ERROR! You need to specify a dir path where perf.data resides"
	echo -e "Usage:\t$ ./perf_script_process.sh <dir where perf.data exists>"
fi
